"""The contact card: the owner-authored top pane of every CRM person.

Everything above the dossier — name, pronouns, relationship, title, company,
location, birthday, and the ranked list of emails and phones — is DERIVED by
default and OVERRIDABLE by the owner. This module owns the override half.

Why an overlay store and not CRM fields
---------------------------------------
The CRM's own records are model-synthesized. `master.json` is rebuilt from
evidence and `profiles/p_*.json` are regenerated by
crm/scripts/synthesize_profiles.py; only the three fields in
data.PROFILE_EDITABLE_FIELDS survive that refresh. An owner correction
written into a synthesized field is a correction with a shelf life, which is
the same trap sendpref.py documents for the send-channel choice. So owner
edits live in Vira's own store (data/contact-cards.json) and are overlaid on
the derived values at read time — the atlas-groups pattern
(atlas.apply_overrides): edits are instant, survive every CRM rebuild, and
cannot corrupt the source data.

Two edits are deliberate exceptions, because they are registry facts rather
than card presentation, and an overlay would leave the app internally
inconsistent (a card reading one name while the feed, brief, and people list
read another):

  - the display NAME writes through to people.json (triage.rename_person);
  - an ADDED email or phone writes through to people.json
    (triage.add_handles), so inbound mail and messages from it actually
    resolve to this person.

Handles carry two independent dimensions
----------------------------------------
RANK — primary / secondary / archived — is which one Vira should USE.
USE — personal / work — is which part of the person's life it belongs to.
They are orthogonal on purpose: a work address can be the primary one, and
knowing an address is personal says nothing about whether it is current.

`archived` is the answer to "this one is out of date". It is kept, kept
resolving inbound (that is how old threads stay joined to the right person),
hidden behind a disclosure rather than cluttering the card, and never
auto-picked for anything outbound. Deleting a handle is deliberately not
offered for that reason; only an unsaved, card-added handle can be dropped.

Rank stays one primary PER KIND rather than per (kind, use): `primary_handle`
answers "which address does Vira write to", and nothing upstream of a reply
draft supplies whether the moment is personal or work, so a second primary
would only make that question ambiguous.

`primary_handle` is what makes the rank load-bearing rather than decorative:
the email-draft path used to take whichever address happened to be first in
the registry, which on a contact carrying nine of them is a coin toss.
"""
import re
import time
import uuid
from pathlib import Path

from . import jsonstore

STORE = Path(__file__).resolve().parent.parent / "data" / "contact-cards.json"

MAX_VALUE = 400          # a card field is a label, not an essay
MAX_CUSTOM = 24          # custom rows per person

RANKS = ("primary", "secondary", "archived")
USES = ("personal", "work")
_RANK_ORDER = {"primary": 0, "": 1, "secondary": 2, "archived": 3}
# `former` was this rank's first name; accept it so a store written before
# the rename keeps meaning what it meant
_RANK_ALIAS = {"former": "archived"}

# Standard rows, in render order. `derive` names where the default comes
# from; None means the field exists only when the owner fills it in.
FIELDS = (
    {"key": "display_name", "label": "Name", "derive": "person.name",
     "placeholder": "Their name"},
    {"key": "pronouns", "label": "Pronouns", "derive": None,
     "placeholder": "they/them"},
    {"key": "relationship", "label": "Relationship", "derive": "relationship",
     "placeholder": "Wife, college friend, client…"},
    {"key": "title", "label": "Title", "derive": "master.title",
     "placeholder": "What they do"},
    {"key": "company", "label": "Company", "derive": "master.company",
     "placeholder": "Where they do it"},
    {"key": "location", "label": "Location", "derive": None,
     "placeholder": "City, state"},
    {"key": "birthday", "label": "Birthday", "derive": None,
     "placeholder": "June 3"},
    {"key": "note", "label": "Note", "derive": None,
     "placeholder": "A line you want on the card"},
)
FIELD_KEYS = tuple(f["key"] for f in FIELDS)
BY_KEY = {f["key"]: f for f in FIELDS}

# Fields that are registry facts, written through instead of overlaid.
WRITE_THROUGH = frozenset({"display_name"})


# ---------- store ----------

def _blank():
    return {"cards": {}}


def _card(s, pid):
    c = s["cards"].setdefault(pid, {})
    c.setdefault("fields", {})
    c.setdefault("handles", {})
    c.setdefault("custom", [])
    return c


def raw(pid):
    """The owner's overrides for one person, with no CRM merge."""
    s = jsonstore.read(STORE, _blank())
    if not isinstance(s, dict) or not isinstance(s.get("cards"), dict):
        return {"fields": {}, "handles": {}, "custom": []}
    c = s["cards"].get(pid) or {}
    return {"fields": c.get("fields") or {}, "handles": c.get("handles") or {},
            "custom": c.get("custom") or [], "updated": c.get("updated")}


def _clean(v):
    return re.sub(r"\s+", " ", str(v or "").strip())[:MAX_VALUE]


# ---------- handles ----------

def handle_key(kind, value):
    """Stable key for a handle. Emails case-fold; phones reduce to their last
    ten digits, so (202) 555-0188 and its +1-prefixed spelling are one
    handle."""
    if kind == "email":
        return "email:" + str(value or "").strip().lower()
    from . import data as crm
    return "phone:" + crm.norm_digits(value)


def format_phone(digits):
    d = re.sub(r"\D", "", digits or "")
    if len(d) == 10:
        return f"({d[:3]}) {d[3:6]}-{d[6:]}"
    return digits or ""


def norm_rank(rank):
    rank = _RANK_ALIAS.get(rank, rank)
    return rank if rank in RANKS else ""


def _handle_rows(person, over):
    """Every known handle for a person, ranked. Registry order is preserved
    inside a rank so an unranked card still reads the way the CRM built it.
    Sorting is by rank ALONE — `use` is shown as a tag rather than used as a
    second sort key, so tagging an address personal does not make the list
    reshuffle under the cursor."""
    h = person.get("handles") or {}
    rows, seen = [], set()

    def add(kind, value, from_card=False):
        value = str(value or "").strip()
        if not value:
            return
        key = handle_key(kind, value)
        if key in seen or key in ("email:", "phone:"):
            return
        seen.add(key)
        meta = over.get(key) or {}
        rows.append({
            "key": key, "kind": kind, "value": value,
            "display": format_phone(value) if kind == "phone" else value,
            "rank": norm_rank(meta.get("rank")),
            "use": meta.get("use") if meta.get("use") in USES else "",
            "added": bool(meta.get("added")) or from_card,
        })

    for e in h.get("emails") or []:
        add("email", e)
    for p in h.get("phones10") or []:
        add("phone", p)
    # a handle the owner added through the card but that has not landed in
    # the registry (an offline write, a fixture-mode CRM) still shows up
    for key, meta in over.items():
        if not meta.get("added"):
            continue
        kind, _, val = key.partition(":")
        if kind in ("email", "phone") and val:
            add(kind, val, from_card=True)

    rows.sort(key=lambda r: _RANK_ORDER.get(r["rank"], 1))
    return rows


def primary_handle(pid, kind="email"):
    """The address Vira should actually use for this person: the one marked
    primary, else the first that is not archived, else None. This is the
    whole point of the ranks — outbound picks a chosen handle, not handles[0].
    """
    from . import data as crm
    person = crm._load()["by_id"].get(pid)
    if not person:
        return None
    rows = [r for r in _handle_rows(person, raw(pid)["handles"])
            if r["kind"] == kind]
    for r in rows:
        if r["rank"] == "primary":
            return r["value"]
    for r in rows:
        if r["rank"] != "archived":
            return r["value"]
    return None


def archived_handles(pid):
    """The set of this person's archived handles, in the normalized spelling a
    caller holds (lowercased email, ten-digit phone). Outbound paths check
    this: "out of date but still stored" has to mean Vira stops using it, or
    the mark is decoration.

    Archiving deliberately does NOT reach resolution — an old address still
    joins its old messages to the right person.
    """
    out = set()
    for key, meta in (raw(pid)["handles"] or {}).items():
        if isinstance(meta, dict) and norm_rank(meta.get("rank")) == "archived":
            _, _, val = key.partition(":")
            if val:
                out.add(val)
    return out


def added_handles():
    """{handle -> pid} for every card-added handle, so data._load can fold
    them into its resolution table (an address the owner just added should
    join the next inbound message to this person, not sit inert)."""
    s = jsonstore.read(STORE, _blank())
    out = {}
    if not isinstance(s, dict) or not isinstance(s.get("cards"), dict):
        return out
    for pid, c in s["cards"].items():
        for key, meta in (c.get("handles") or {}).items():
            if not isinstance(meta, dict) or not meta.get("added"):
                continue
            kind, _, val = key.partition(":")
            if val and kind in ("email", "phone"):
                out[val] = pid
    return out


# ---------- the merged card ----------

def compose(pid, detail=None):
    """The card the UI renders: every standard row with its derived default,
    the owner's override where one exists, and the ranked handle list.

    `source` is the honest provenance of each row — "owner" for something the
    owner typed, "crm" for a value Vira derived from the CRM, "empty" for a
    row waiting to be filled. The card shows the difference; a contact record
    that cannot say which parts are guesses is not worth trusting.
    """
    from . import data as crm
    if detail is None:
        detail = crm.get_person(pid)
    if not detail:
        return None
    person = detail["person"]
    master = detail.get("master") or {}
    prof = detail.get("profile") or {}
    over = raw(pid)

    derived = {
        "person.name": person.get("name") or "",
        "relationship": (prof.get("relationship_class")
                         or master.get("relationship") or ""),
        "master.title": master.get("title") or "",
        "master.company": master.get("company") or "",
    }

    fields = []
    for f in FIELDS:
        d = _clean(derived.get(f["derive"])) if f["derive"] else ""
        owned = over["fields"].get(f["key"])
        has_owned = isinstance(owned, str) and owned.strip() != ""
        value = _clean(owned) if has_owned else d
        fields.append({
            "key": f["key"], "label": f["label"], "value": value,
            "placeholder": f["placeholder"],
            "derived": d,
            "source": "owner" if has_owned else ("crm" if d else "empty"),
        })

    custom = [{"id": c.get("id") or "", "label": _clean(c.get("label")),
               "value": _clean(c.get("value"))}
              for c in over["custom"] if isinstance(c, dict)][:MAX_CUSTOM]

    return {
        "pid": pid,
        "fields": fields,
        "custom": custom,
        "handles": _handle_rows(person, over["handles"]),
        "updated": over.get("updated"),
    }


# ---------- saving ----------

def _describe(before, after, note):
    """The change list, in the owner's language. It is both what the save
    dialog showed and what gets filed to the journal — the two must say the
    same thing, so they are generated once, here."""
    lines = []
    b_fields = {f["key"]: f for f in before["fields"]}
    for f in after["fields"]:
        old = b_fields.get(f["key"], {}).get("value", "")
        if f["value"] == old:
            continue
        label = f["label"]
        if not old:
            lines.append(f'{label} set to "{f["value"]}"')
        elif not f["value"]:
            lines.append(f'{label} cleared (was "{old}")')
        else:
            lines.append(f'{label} changed from "{old}" to "{f["value"]}"')

    b_custom = {c["label"].lower(): c["value"] for c in before["custom"]}
    for c in after["custom"]:
        old = b_custom.pop(c["label"].lower(), None)
        if old is None:
            lines.append(f'{c["label"]}: "{c["value"]}" (new field)')
        elif old != c["value"]:
            lines.append(f'{c["label"]} changed from "{old}" to "{c["value"]}"')
    for label in b_custom:
        lines.append(f"{label} removed from the card")

    b_h = {h["key"]: h for h in before["handles"]}
    for h in after["handles"]:
        old = b_h.get(h["key"])
        what = h["display"]
        if old is None:
            bits = [f"{h['kind']} {what} added"]
            if h["use"]:
                bits.append(f"as a {h['use']} {h['kind']}")
            if h["rank"]:
                bits.append(f"marked {h['rank']}")
            lines.append(", ".join(bits))
            continue
        if old["rank"] != h["rank"]:
            if h["rank"] == "archived":
                lines.append(f"{what} archived — out of date, kept on file")
            elif h["rank"]:
                lines.append(f"{what} marked {h['rank']} {h['kind']}")
            else:
                lines.append(f"{what} no longer marked {old['rank']}")
        if old["use"] != h["use"]:
            lines.append(f"{what} is a {h['use']} {h['kind']}" if h["use"]
                         else f"{what} no longer marked {old['use']}")
    if note:
        lines.append(note)
    return lines


def _journal_text(name, lines, note):
    """The note filed to the brief journal. Phrased as things the owner is
    telling Vira — already applied to the card — so the integration pass
    files what they MEAN (a fact, a loop, an instruction for a session with
    real access to fix the CRM's own synthesized record) instead of asking
    for the edit to be made again."""
    head = f"I updated {name}'s contact card:"
    body = "\n".join(f"- {ln}" for ln in lines if ln != note)
    tail = f"\n\n{note}" if note else ""
    return f"{head}\n{body}{tail}".strip()


def save(pid, draft, integrate=True):
    """Apply an edited card. Deterministic and instant: the structured diff
    lands in the store (and, for the two write-through cases, in the CRM
    registry) before anything AI-shaped runs. Then the change is filed to the
    brief journal, where the existing integration pass decides what it means
    — a durable fact, a loop, or an instruction that needs a real session.
    Saving a card IS telling Vira; this is the seam that makes that true.

    Returns {card, changes, note_id, warnings}.
    """
    from . import data as crm, journal, triage
    person = crm._load()["by_id"].get(pid)
    if not person:
        raise KeyError(pid)
    before = compose(pid)
    warnings = []

    fields = draft.get("fields") or {}
    if not isinstance(fields, dict):
        raise ValueError("fields must be an object")
    custom = draft.get("custom")
    handles = draft.get("handles") or {}
    added = draft.get("added") or []
    note = _clean(draft.get("note"))[:MAX_VALUE]

    # The overlay is instance-local; registry edits use the connected CRM.

    # --- write-through: the name is registry data, not card decoration
    new_name = _clean(fields.get("display_name")) if "display_name" in fields \
        else None
    if new_name and new_name != (person.get("name") or ""):
        triage.rename_person(pid, new_name)

    # --- write-through: an added handle must actually resolve
    fresh = []
    for h in added:
        if not isinstance(h, dict):
            continue
        kind = h.get("kind")
        value = _clean(h.get("value"))
        if kind not in ("email", "phone") or not value:
            continue
        if kind == "email" and "@" not in value:
            warnings.append(f"{value} does not look like an email — skipped")
            continue
        if kind == "phone" and len(re.sub(r"\D", "", value)) < 10:
            warnings.append(f"{value} does not look like a phone number "
                            "— skipped")
            continue
        owner = crm.resolve_handle(value)
        if owner and owner != pid:
            warnings.append(f"{value} already belongs to another contact "
                            "— skipped")
            continue
        fresh.append({"kind": kind, "value": value})
    if fresh:
        try:
            triage.add_handles(pid, fresh)
        except (OSError, ValueError, KeyError) as e:
            warnings.append(f"could not add to the CRM registry ({e}) — the "
                            "handle is kept on the card")

    # --- the overlay
    def fn(s):
        s.setdefault("cards", {})
        c = _card(s, pid)
        for k, v in fields.items():
            if k not in FIELD_KEYS or k in WRITE_THROUGH:
                continue
            v = _clean(v)
            if v:
                c["fields"][k] = v
            else:
                c["fields"].pop(k, None)
        if isinstance(custom, list):
            rows = []
            for row in custom[:MAX_CUSTOM]:
                if not isinstance(row, dict):
                    continue
                label, value = _clean(row.get("label")), _clean(row.get("value"))
                if not label:
                    continue
                rows.append({"id": row.get("id") or "f_" + uuid.uuid4().hex[:8],
                             "label": label, "value": value})
            c["custom"] = rows
        for key, meta in handles.items():
            if not isinstance(meta, dict) or not isinstance(key, str):
                continue
            kind, _, val = key.partition(":")
            if kind not in ("email", "phone") or not val:
                continue
            cur = dict(c["handles"].get(key) or {})
            if "rank" in meta:
                rank = norm_rank(meta.get("rank"))
                if rank:
                    cur["rank"] = rank
                else:
                    cur.pop("rank", None)
            if "use" in meta:
                use = meta.get("use")
                if use in USES:
                    cur["use"] = use
                else:
                    cur.pop("use", None)
            if cur:
                c["handles"][key] = cur
            else:
                c["handles"].pop(key, None)
        for h in fresh:
            key = handle_key(h["kind"], h["value"])
            c["handles"].setdefault(key, {})["added"] = True
        # one primary per kind: promoting a handle demotes the incumbent
        for kind in ("email", "phone"):
            claimed = [k for k, m in c["handles"].items()
                       if k.startswith(kind + ":") and m.get("rank") == "primary"]
            wanted = [k for k in claimed
                      if (handles.get(k) or {}).get("rank") == "primary"]
            keep = wanted[-1] if wanted else (claimed[0] if claimed else None)
            for k in claimed:
                if k != keep:
                    c["handles"][k]["rank"] = "secondary"
        c["updated"] = time.strftime("%Y-%m-%dT%H:%M:%S")

    jsonstore.mutate(STORE, fn, _blank(), indent=1, ensure_ascii=False)
    crm.invalidate()   # a rename or a new handle changes what the CRM serves

    after = compose(pid)
    changes = _describe(before, after, note)
    note_id = None
    if changes and integrate:
        try:
            entry = journal.add(
                _journal_text(after["fields"][0]["value"] or person["name"],
                              changes, note),
                person_id=pid,
                context="Contact card — these edits are already applied in "
                        "Vira; file what they mean")
            note_id = entry["id"]
        except (ValueError, KeyError) as e:   # the card save still stands
            warnings.append(f"could not file a journal note ({e})")
    return {"card": after, "changes": changes, "note_id": note_id,
            "warnings": warnings}
