"""Under the hood — what a standing loop actually IS, and editing it.

A trigger part in The Forge · Flows says its name, its cadence,
and one sentence the seed happened to carry. Everything that decides what
it DOES — the prompt composed at dispatch, the in-process function an
internal token resolves to, the scheduler that fires it — lived only in
the source. So the panel a stranger meets during onboarding described
five loops it could not open.

This module opens them. ``hood(r)`` resolves one routine into three
things, all DERIVED at read time so none of them can drift from the code
they describe:

  facts   the trigger, the engine, the blast radius — what it writes,
          whether it costs a model call, what it tells you afterwards.
  steps   how the loop actually fires, in order, in plain English.
  parts   the FULL text of every piece: the prompt (stored, or composed
          live), the Python function an internal token runs, and the
          shared scheduler machinery underneath all of them.

EDITING. A part is one of three kinds and each is written back a
different way:

  field   a routine field (name, prompt, cadence, description) — goes
          through ``routines.save_routine``, the same validated path the
          form uses. Takes effect on the next tick.
  code    a Python function in this checkout. Spliced back over the
          function's CURRENT line range, which is re-derived from the
          file's AST at write time rather than trusted from the read —
          two edits in a row shift every line under them, and a stale
          range would write into the middle of a neighbour. The merged
          file must PARSE and must still define the symbol; a file that
          fails either is never written. Needs a restart.
  derived a live composition (the muse's prompt, the room sweep) — shown
          in full so you can see what actually goes to the model, but not
          editable HERE: it is generated by the code part beside it, and
          an edit would be overwritten by the next run.

Every code write snapshots the whole file to ``data/backups/code/`` first
(that is what ``revert`` restores), and ``restore_shipped`` goes further
back, to the version in git. Editing is allowed on every instance — see
``writable`` for why a test clone is not the exception it looks like —
but only a supervised one offers the restart that loads the change.
"""
from __future__ import annotations

import ast
import hashlib
import os
import re
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path

from . import gitutil, routines

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "server"
BACKUP_DIR = ROOT / "data" / "backups" / "code"
KEEP_BACKUPS = 20
MAX_EDIT_BYTES = 400 * 1024

# An internal prompt token -> the CHAIN of functions it actually runs, as
# (module, symbol, title, note). A chain rather than one entry because the
# entry point is sometimes a trampoline: atlas.refresh is four lines that
# spawn a thread, and showing only those four would answer "what does this
# loop do?" with "it starts something". dispatch() is the authority for
# which token exists; the test suite pins the two against each other so a
# token cannot ship unexplained.
TOKENS = {
    "__refresh_groupings__": [
        ("radar", "refresh_groupings", "What this loop runs", ""),
    ],
    "__refresh_intros__": [
        ("radar", "refresh_groupings", "What this loop runs", ""),
    ],
    "__refresh_atlas__": [
        ("atlas", "refresh", "What this loop runs",
         "A thread spawn, so the scheduler is never blocked by a rebuild. "
         "The rebuild itself is below."),
        ("atlas", "build_graph", "The rebuild itself",
         "Every signal the graph fuses, and the order it fuses them in."),
    ],
    "__refresh_reconnect__": [
        ("reconnect", "refresh", "What this loop runs", ""),
    ],
    "__module_map__": [
        ("modulemap", "refresh_prompt", "How this loop's prompt is built",
         ""),
    ],
    "__room_scout__": [
        ("readingroom", "refresh_all_prompt",
         "How this loop's prompt is built",
         "One sweep across every room you have."),
        ("readingroom", "update_prompt", "The contract each room gets",
         "What a refresh is told to do with a room it is rebuilding — "
         "carry everything forward, research only what is new."),
    ],
    "__orphan_sweep__": [
        ("orphanwork", "refresh", "What this loop runs", ""),
        ("orphanwork", "sweep", "The inventory itself",
         "Every worktree and claude/* branch carrying unlanded work — "
         "plain git plus a job-ledger join, no model call. A branch a "
         "live session owns is not orphan work and is excluded."),
    ],
    "__room_ingest__": [
        ("fullingest", "run_all", "What this loop runs", ""),
        ("fullingest", "stage", "Staging the material",
         "Every un-staged room item's material fetched into the vault's "
         "raw/reading-room/ — YouTube captions via yt-dlp, article text "
         "via a minimal fetch. Deterministic; no model call."),
        ("fullingest", "reconcile", "Linking what was synthesized",
         "Items whose source-summary landed in wiki/ get their vault "
         "field written and their obsolete pointer note retired to "
         "pending-user-deletion/."),
    ],
    "__lesson_recurrence__": [
        ("lessonwatch", "run_pass", "What this loop runs",
         "Rung 1 is deterministic (gather, score, count restatements); "
         "rung 2 adjudicates candidates with one model call per rule, "
         "every verdict grounded by a verbatim quote or dropped."),
        ("lessonwatch", "_propose_promotion", "The proposal it can stage",
         "At threshold a tier-2 rule stages the WORK of building its "
         "mechanism as a proposed idea in Cues. It never writes "
         "the corrections ledger itself."),
    ],
}

# Tokens whose function COMPOSES a prompt and hands it to a model session,
# rather than doing the work in process. The distinction is the whole
# difference between "free, works with no AI connected" and "spends a
# model call", so the panel must never blur it.
COMPOSERS = {"__module_map__", "__room_scout__"}

# Internal tokens that SPEND MODEL CALLS in process — a third shape the
# panel must not blur into either neighbour: no session is dispatched
# (unlike a composer), but "free, works with no AI connected" would be
# false (unlike the refresh tokens), and dispatch() gates them behind
# _ai_ready for exactly that reason.
MODEL_INTERNAL = {"__lesson_recurrence__"}

# What a run actually changes. Keyed by token, then by kind. Plain English
# on purpose: this is the line that answers "what happens if I let it run?"
EFFECTS = {
    "__refresh_groupings__":
        "data/radar-groupings.json — the groupings and conversation "
        "markers on People · Networking.",
    "__refresh_intros__":
        "data/radar-groupings.json — the groupings on People · Networking.",
    "__refresh_atlas__":
        "data/atlas-graph.json — the Visual Network graph (edges, "
        "clusters, and the narration on the strongest links).",
    "__refresh_reconnect__":
        "data/reconnect.json — the Reconnect rows on People · Networking.",
    "__module_map__":
        "the module registry behind the System Map, and only through the "
        "validated update_module_map tool — the session cannot write it "
        "directly.",
    "__room_scout__":
        "each reading room, rebuilt in place. You are pinged per room "
        "that gained items.",
    "__orphan_sweep__":
        "data/orphan-work.json — the unlanded-work rows in The Forge · Runs. "
        "You are pinged when a genuinely new orphan appears, never on "
        "the first-ever sweep.",
    "__room_ingest__":
        "the vault's raw/reading-room/ (staged material), each room store's "
        "vault fields, and pending-user-deletion/ (retired pointer notes). "
        "The wiki summaries themselves are written by the vault's own "
        "nightly ingest, not this loop.",
    "__lesson_recurrence__":
        "data/lesson-recurrence.json — the Rules panel under The Forge · "
        "Record; a tier-2 rule at threshold stages a proposed idea in "
        "Cues, and a tier-1 recurrence pings you (the guard did "
        "not hold). It NEVER writes the corrections ledger itself.",
}
KIND_EFFECTS = {
    "muse":
        "nothing on its own. Ideas land in The Forge · Cues as proposals — "
        "nothing builds until you approve one.",
}

SHARED = [
    ("routines", "is_due", "Whether a loop is due",
     "The cadence test. Reads the loop's last run against its schedule."),
    ("routines", "dispatch", "Dispatching one loop",
     "Turns a due loop into a run: the internal branches, the composed "
     "prompts, and the launch into a durable session."),
    ("routines", "Scheduler.tick", "The 60-second tick",
     "The heartbeat. Settles finished runs, then dispatches whatever is "
     "due and not already running."),
]


# ---------------------------------------------------------------- source

def _src_path(module: str) -> Path:
    """The file for a server module name, validated to live in this
    checkout's server/ directory. The only door to the filesystem here."""
    if not re.fullmatch(r"[a-z_][a-z0-9_]{0,40}", module or ""):
        raise ValueError(f"bad module name: {module!r}")
    p = (SRC_DIR / f"{module}.py").resolve()
    if p.parent != SRC_DIR.resolve() or not p.is_file():
        raise ValueError(f"no such module: {module}")
    return p


def _find(tree: ast.AST, symbol: str):
    """The AST node for a dotted symbol ('refresh', 'Scheduler.tick')."""
    node = tree
    for name in symbol.split("."):
        body = getattr(node, "body", None)
        if body is None:
            return None
        node = next(
            (n for n in body
             if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef,
                               ast.ClassDef)) and n.name == name), None)
        if node is None:
            return None
    return node


def locate(module: str, symbol: str):
    """(path, first_line, last_line) for a symbol, read from the file's
    CURRENT text. Deliberately not inspect.getsourcelines: an edited
    module is stale in memory until a restart, and the range a write
    splices over has to describe the file on disk, not the import."""
    path = _src_path(module)
    text = path.read_text(encoding="utf-8")
    node = _find(ast.parse(text), symbol)
    if node is None:
        raise ValueError(f"{module}.{symbol} not found")
    first = min([node.lineno] + [d.lineno for d in
                                 getattr(node, "decorator_list", [])])
    return path, first, node.end_lineno


def read_symbol(module: str, symbol: str):
    path, a, b = locate(module, symbol)
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    return "".join(lines[a - 1:b])


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------- parts

def _part(pid, title, text, *, kind, lang="text", note="", editable=False,
          module="", symbol="", shared=False):
    body = text or ""
    return {"id": pid, "title": title, "note": note, "kind": kind,
            "lang": lang, "editable": bool(editable), "shared": bool(shared),
            "module": module, "symbol": symbol,
            "path": _rel(_src_path(module)) if module else "",
            "lines": len(body.splitlines()),
            "sha": hashlib.sha256(body.encode("utf-8")).hexdigest()[:12],
            "text": body}


def _code_part(pid, module, symbol, title, note, shared=False):
    try:
        text = read_symbol(module, symbol)
    except (ValueError, OSError) as e:      # a renamed function, honestly
        return _part(pid, title, "", kind="missing",
                     note=f"could not be located in the source: {e}")
    return _part(pid, title, text, kind="code", lang="python", note=note,
                 editable=True, module=module, symbol=symbol, shared=shared)


def _composed(token):
    """The prompt a composing token produces right now, or None."""
    try:
        if token == "__module_map__":
            from . import modulemap
            return modulemap.refresh_prompt()
        if token == "__room_scout__":
            from . import readingroom
            return readingroom.refresh_all_prompt() or ""
    except Exception as e:  # noqa: BLE001 — a preview never breaks the panel
        return f"(could not compose right now: {e})"
    return None


def parts(r) -> list:
    """Every piece of one routine, loop-specific first."""
    out = []
    kind = r.get("kind")
    token = (r.get("prompt") or "").strip()

    if kind == "muse":
        out.append(_code_part(
            "code:muse", "routines", "_muse_prompt",
            "How the muse's prompt is built",
            "Composed fresh at every dispatch, so the backlog it is told "
            "not to duplicate is always the current one. This is the "
            "editable half — the text below is its output."))
        try:
            out.append(_part("derived:muse", "The prompt it will send today",
                             routines._muse_prompt(), kind="derived",
                             note="Generated by the function above. Shown "
                                  "in full so nothing is hidden; edit the "
                                  "function to change it."))
        except Exception:  # noqa: BLE001
            pass
    elif kind == "circuit":
        out.append(_part("field:circuit", "The recipe it runs",
                         r.get("circuit_id") or "(none chosen)",
                         kind="derived",
                         note="Circuit-backed systems are edited in The "
                              "Forge · Flows, where every stage unfolds."))
    elif token in TOKENS:
        composes = token in COMPOSERS
        lead = ("Composed fresh at every dispatch and handed to a session."
                if composes else
                "Runs in process, right here in the server. No model call, "
                "no cost, and it works on a machine with no AI connected.")
        for i, (module, symbol, title, note) in enumerate(TOKENS[token]):
            out.append(_code_part(
                f"code:token{i or ''}", module, symbol, title,
                (lead + (" " + note if note else "")) if i == 0 else note))
        if composes:
            text = _composed(token)
            if text is not None:
                out.append(_part(
                    "derived:token", "The prompt it would send right now",
                    text or "(nothing to do — this loop would no-op)",
                    kind="derived",
                    note="Generated by the function above."))
    else:
        out.append(_part("field:prompt", "The prompt this loop runs",
                         r.get("prompt") or "", kind="field", editable=True,
                         note="Sent verbatim to a fresh session at every "
                              "run. Plain text — edit it freely."))

    for module, symbol, title, note in SHARED:
        out.append(_code_part(f"shared:{module}.{symbol}", module, symbol,
                              title, note, shared=True))
    return out


# ---------------------------------------------------------------- explain

def _next_due(r):
    if not r.get("enabled"):
        return None
    now = datetime.now().astimezone()
    if r.get("daily_at"):
        try:
            hh, mm = str(r["daily_at"]).split(":")
            gate = now.replace(hour=int(hh), minute=int(mm), second=0,
                               microsecond=0)
        except (ValueError, AttributeError):
            return None
        if routines.is_due(r, now):
            return now
        return gate if now < gate else gate + timedelta(days=1)
    hours = float(r.get("every_hours") or 0)
    if hours <= 0:
        return None
    last = r.get("last_run")
    if not last:
        return now
    try:
        last_dt = datetime.fromisoformat(last).astimezone()
    except ValueError:
        return now
    due = last_dt + timedelta(hours=hours)
    return max(due, now) if due > now else now


def engine_of(r) -> str:
    """internal | session | circuit — the three ways a loop can run."""
    if r.get("kind") == "circuit":
        return "circuit"
    token = (r.get("prompt") or "").strip()
    if token in TOKENS and token not in COMPOSERS:
        return "internal"
    return "session"


def facts(r) -> list:
    """The labeled facts, in reading order. Each {label, value, tone}."""
    engine = engine_of(r)
    cad = ("daily at " + r["daily_at"]) if r.get("daily_at") else (
        f"every {_hours(r.get('every_hours'))}" if r.get("every_hours")
        else "no cadence set")
    nxt = _next_due(r)
    if not r.get("enabled"):
        nxt_label = "paused"
    elif routines.is_due(r):
        nxt_label = "due now — the next tick will run it"
    else:
        nxt_label = _when(nxt) if nxt else "unknown"
    rows = [
        {"label": "Runs", "value": cad},
        {"label": "Next", "value": nxt_label,
         "tone": "dim" if not r.get("enabled") else ""},
        {"label": "Engine", "value": (
            "in process — spends model calls for its adjudication step, "
            "so it waits for a connected AI"
            if engine == "internal"
            and (r.get("prompt") or "").strip() in MODEL_INTERNAL else {
                "internal": "in process — no model call, no cost",
                "circuit": "a multi-stage recipe",
                "session": "a live agent session, with a terminal",
            }[engine])},
    ]
    if engine == "session":
        rows.append({"label": "Permission",
                     "value": _mode_label(r.get("mode"))})
    rows.append({"label": "Writes", "value": effect_of(r)})
    rows.append({"label": "Tells you",
                 "value": ("an iMessage when a run finishes"
                           if r.get("notify") else
                           "nothing — it runs silently")})
    last = []
    if r.get("last_run"):
        last.append(_when(_parse(r["last_run"])))
    if r.get("last_status"):
        last.append(r["last_status"])
    rows.append({"label": "Last run",
                 "value": " · ".join(last) if last else "never run",
                 "tone": "warn" if "skip" in (r.get("last_status") or "")
                 else ""})
    return rows


def effect_of(r) -> str:
    token = (r.get("prompt") or "").strip()
    if token in EFFECTS:
        return EFFECTS[token]
    if r.get("kind") in KIND_EFFECTS:
        return KIND_EFFECTS[r["kind"]]
    if r.get("kind") == "circuit":
        return "whatever its recipe's stages write."
    return ("whatever the prompt asks for — an ordinary session, so it can "
            "touch anything a session can.")


def steps(r) -> list:
    """How this loop actually fires, in order. Derived from its shape, so
    a loop that changes kind gets a different explanation for free."""
    engine = engine_of(r)
    token = (r.get("prompt") or "").strip()
    cad = ("at " + r["daily_at"] + " each day") if r.get("daily_at") else (
        "every " + _hours(r.get("every_hours")))
    out = [{
        "title": "The scheduler notices",
        "body": "Vira's scheduler wakes every 60 seconds and asks each "
                f"loop whether it is due. This one is due {cad}. A loop "
                "whose previous run is still going is left alone rather "
                "than started twice."}]
    if engine == "internal":
        module, symbol = TOKENS[token][0][:2]
        if token in MODEL_INTERNAL:
            out.append({
                "title": "It runs in process",
                "body": f"No session is dispatched: Vira calls "
                        f"{module}.{symbol}() directly, in its own "
                        "thread. Its first rung is deterministic, but "
                        "its adjudication step spends model calls, so "
                        "the scheduler skips this loop until an AI is "
                        "connected."})
        else:
            out.append({
                "title": "It runs in process",
                "body": f"No prompt and no session: Vira calls "
                        f"{module}.{symbol}() directly, in its own thread. "
                        "That is why this loop costs nothing and keeps "
                        "working on a machine with no AI connected."})
        out.append({"title": "It writes", "body": effect_of(r)})
        out.append({
            "title": "You see the result where it lives",
            "body": "There is no terminal to open — nothing was dispatched. "
                    "The row below records the run, and the module it "
                    "refreshed shows the new data."})
        return out
    if engine == "circuit":
        out.append({
            "title": "It starts a recipe",
            "body": f"The recipe '{r.get('circuit_id') or '(none)'}' runs as "
                    "a multi-stage pipeline — each stage its own session, "
                    "handing its output to the next."})
        out.append({
            "title": "You watch it in Runs",
            "body": "The run appears under The Forge · Runs as a stage "
                    "graph you can click into."})
        return out
    if r.get("kind") == "muse":
        out.append({
            "title": "The prompt is composed fresh",
            "body": "Vira reads the current backlog and writes the prompt "
                    "around it, so the muse is told exactly what not to "
                    "propose again. The composed text is below."})
    elif token in COMPOSERS:
        module, symbol = TOKENS[token][0][:2]
        out.append({
            "title": "The prompt is composed fresh",
            "body": f"{module}.{symbol}() builds the prompt at dispatch "
                    "from the current state, so every run works from what "
                    "is true that morning."})
    else:
        out.append({
            "title": "It sends your prompt",
            "body": "The text below goes to a fresh session verbatim. "
                    "Nothing is added except Vira's standing preamble."})
    out.append({
        "title": "A real session runs it",
        "body": "The run is an ordinary durable job: its own detached "
                "process, a live terminal under The Forge · Runs, a row in the "
                "ledger, and it survives a Vira restart. It runs on "
                f"{_mode_label(r.get('mode'))}."})
    out.append({
        "title": "It writes",
        "body": effect_of(r)})
    out.append({
        "title": "It reports",
        "body": ("Vira iMessages you when the run finishes."
                 if r.get("notify") else
                 "It finishes quietly — check the row below, or its "
                 "terminal under The Forge · Runs.")})
    out.append({
        "title": "If no AI is connected",
        "body": "The run is skipped and the loop stays due, so it fires as "
                "soon as you connect a provider instead of losing the "
                "whole cadence period."})
    return out


def _mode_label(mode):
    return {
        "manual": "manual — every risky call asks you first",
        "acceptEdits": "accept edits — file edits land unasked, commands ask",
        "bypassPermissions": "bypass — nothing asks (the default)",
    }.get(_norm_mode(mode), "bypass — nothing asks (the default)")


def _norm_mode(mode):
    try:
        from . import session
        return session.norm_mode(mode, "bypassPermissions")
    except Exception:  # noqa: BLE001
        return mode or "bypassPermissions"


def _hours(h):
    try:
        h = float(h or 0)
    except (TypeError, ValueError):
        return "?"
    if h <= 0:
        return "?"
    if h % 24 == 0:
        d = int(h // 24)
        return "24 hours" if d == 1 else f"{d} days"
    return f"{h:g} hours"


def _parse(s):
    try:
        return datetime.fromisoformat(s).astimezone()
    except (TypeError, ValueError):
        return None


def _when(dt):
    if not dt:
        return "unknown"
    now = datetime.now().astimezone()
    delta = (dt - now).total_seconds()
    ago = delta < 0
    secs = abs(delta)
    if secs < 90:
        return "just now" if ago else "in under a minute"
    for size, name in ((3600, "minute"), (86400, "hour"), (86400 * 7, "day")):
        if secs < size:
            step = size // 60 if name == "minute" else (
                3600 if name == "hour" else 86400)
            n = int(secs // step)
            unit = name + ("" if n == 1 else "s")
            return f"{n} {unit} ago" if ago else f"in {n} {unit}"
    return dt.strftime("%-d %b, %H:%M") if not _is_win() \
        else dt.strftime("%d %b, %H:%M")


def _is_win():
    from . import settings
    return settings.IS_WIN


def hood(r) -> dict:
    ps = parts(r)
    # Per-FILE, not per-part: two parts of routines.py share one backup
    # stack, so a revert offered on one is the same revert offered on the
    # other. Answering it once keeps the two buttons from disagreeing.
    files = {p["module"]: state(p["module"]) for p in ps if p["module"]}
    return {"id": r["id"], "name": r.get("name") or r["id"],
            "engine": engine_of(r), "kind": r.get("kind"),
            "description": r.get("description") or "",
            "facts": facts(r), "steps": steps(r), "parts": ps,
            "files": files, "writable": writable()}


# ---------------------------------------------------------------- writing

def writable() -> dict:
    """Source edits and restart follow the checkout and supervisor serving this instance."""
    from . import update
    root = str(ROOT)
    kind, name = update.supervisor()
    return {"ok": True, "root": root, "restart": bool(name),
            "reason": f"Edits land in this checkout ({root})."}


class EditError(ValueError):
    """A refused edit. Carries the reason the panel shows verbatim."""


def _guard():
    w = writable()
    if not w["ok"]:
        raise EditError(w["reason"])


def _backup(path: Path) -> Path:
    """Snapshot the file before it is touched.

    The name ALWAYS carries a zero-padded sequence, never only on a
    collision: revert reads `sorted(...)[-1]` as "the newest", and a bare
    `<stamp>.py` sorts AFTER `<stamp>-1.py` ('-' is 45, '.' is 46), so two
    saves in the same second would have handed revert the older file. Every
    name shaped alike keeps lexical order and chronological order the same
    thing."""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    n = 0
    dest = BACKUP_DIR / f"{path.stem}.{stamp}-{n:03d}.py"
    while dest.exists():
        n += 1
        dest = BACKUP_DIR / f"{path.stem}.{stamp}-{n:03d}.py"
    dest.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    old = sorted(BACKUP_DIR.glob(f"{path.stem}.*.py"))
    for stale in old[:-KEEP_BACKUPS]:
        try:
            stale.unlink()
        except OSError:
            pass
    return dest


def backups(module: str) -> list:
    """Newest first: what revert has to offer for this file."""
    path = _src_path(module)
    out = []
    for p in sorted(BACKUP_DIR.glob(f"{path.stem}.*.py"), reverse=True):
        try:
            out.append({"file": p.name,
                        "at": datetime.fromtimestamp(
                            p.stat().st_mtime, timezone.utc).isoformat(
                                timespec="seconds")})
        except OSError:
            pass
    return out


def _write(path: Path, text: str):
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def write_symbol(module: str, symbol: str, text: str) -> dict:
    """Splice new source over a function, or refuse and change nothing.

    Three checks, in this order, because each one only means anything if
    the one before it passed: the replacement is a plausible size; the
    MERGED file parses; and the symbol still exists in it afterwards. A
    replacement that parses on its own can still break the file it lands
    in (indentation, a stray dedent), which is why the parse is of the
    whole merged text and never of the fragment."""
    _guard()
    if len(text.encode("utf-8")) > MAX_EDIT_BYTES:
        raise EditError("that is too large to be one function")
    path, a, b = locate(module, symbol)      # re-derived NOW, never trusted
    original = path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)
    body = text if text.endswith("\n") else text + "\n"
    merged = "".join(lines[:a - 1]) + body + "".join(lines[b:])
    if merged == original:
        return {"changed": False, "path": _rel(path)}
    try:
        tree = ast.parse(merged)
    except SyntaxError as e:
        # the parser counts lines in the MERGED file, which means nothing to
        # someone reading the one function they just typed
        n = e.lineno or 0
        body_lines = len(body.splitlines())
        where = (f"line {n - a + 1} of what you typed"
                 if a <= n < a + body_lines else f"line {n} of the file")
        raise EditError(f"that would not parse — {where}: {e.msg}. "
                        "Nothing was written.") from None
    if _find(tree, symbol) is None:
        raise EditError(
            f"the replacement no longer defines {symbol} — rename it back, "
            "or make the change in a session instead. Nothing was written.")
    backup = _backup(path)
    _write(path, merged)
    return {"changed": True, "path": _rel(path), "backup": backup.name,
            "restart": writable()["restart"]}


def revert(module: str) -> dict:
    """Undo the last edit to this file by restoring its newest backup —
    which is the file as it stood BEFORE that edit, since the snapshot is
    taken on the way in. Consumes the snapshot, so pressing revert twice
    steps back twice."""
    _guard()
    path = _src_path(module)
    snaps = sorted(BACKUP_DIR.glob(f"{path.stem}.*.py"), reverse=True)
    if not snaps:
        raise EditError("there is no backup to go back to")
    text = snaps[0].read_text(encoding="utf-8")
    try:
        ast.parse(text)
    except SyntaxError as e:                 # a snapshot should always parse
        raise EditError(f"that backup is unusable: {e.msg}") from None
    _write(path, text)
    try:
        snaps[0].unlink()
    except OSError:
        pass
    return {"path": _rel(path), "from": snaps[0].name,
            "restart": writable()["restart"], "remaining": len(snaps) - 1}


def shipped(module: str):
    """The committed version of this file, or None when git cannot say."""
    path = _src_path(module)
    try:
        out = gitutil.git(ROOT, "show", f"HEAD:{_rel(path)}")
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout if out.returncode == 0 else None


def modified(module: str) -> bool:
    ship = shipped(module)
    if ship is None:
        return False
    return ship != _src_path(module).read_text(encoding="utf-8")


def restore_shipped(module: str) -> dict:
    """Back to the version in git — the way out when several edits have
    piled up and stepping back one at a time is not what you want."""
    _guard()
    ship = shipped(module)
    if ship is None:
        raise EditError("git cannot tell me what shipped for this file")
    path = _src_path(module)
    if ship == path.read_text(encoding="utf-8"):
        return {"path": _rel(path), "changed": False}
    _backup(path)
    _write(path, ship)
    return {"path": _rel(path), "changed": True,
            "restart": writable()["restart"]}


def apply_part(r, part_id: str, text: str) -> dict:
    """Write one part back. The routine's own fields go through
    save_routine — the validated path the form already uses — so a
    cadence typed here is checked exactly as one typed there."""
    _guard()
    found = next((p for p in parts(r) if p["id"] == part_id), None)
    if not found:
        raise EditError("unknown part")
    if not found["editable"]:
        raise EditError(f"{found['title']} is generated — "
                        "edit the code that produces it instead")
    if found["kind"] == "code":
        return write_symbol(found["module"], found["symbol"], text)
    field = part_id.split(":", 1)[1]
    routines.save_routine({field: text}, rid=r["id"])
    return {"changed": True, "field": field, "restart": False}


# ---------------------------------------------------------------- meta

def state(module: str) -> dict:
    """What the revert controls should offer for one file."""
    try:
        return {"backups": backups(module), "modified": modified(module)}
    except (ValueError, OSError):
        return {"backups": [], "modified": False}


__all__ = ["hood", "parts", "facts", "steps", "engine_of", "effect_of",
           "apply_part", "write_symbol", "revert", "restore_shipped",
           "state", "backups", "modified", "writable", "EditError",
           "read_symbol", "locate", "TOKENS", "COMPOSERS"]
